name: sample_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_state_notifier: ^0.7.0
  flutter_riverpod: ^0.14.0
  freezed_annotation:
  webview_flutter: ^2.0.0
  chopper: ^4.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed:
  build_runner: ^2.0.6
  chopper_generator: ^4.0.0

flutter:

  uses-material-design: true